var cart=JSON.parse(sessionStorage.getItem("mp-cart")||"[]"),current=null,grid=document.getElementById("grid");
function render(filter){var out="";products.forEach(function(p,i){if(filter!=="Todos"&&p.cat!==filter)return;out+='<article class="card" data-i="'+i+'"><div class="card-media"><img src="'+p.img+'" alt="'+p.name+'" loading="lazy"></div><div class="card-body"><div class="tag">'+p.cat+'</div><h3>'+p.name+'</h3><p>Consultar disponibilidade</p></div></article>'});grid.innerHTML=out}
function save(){sessionStorage.setItem("mp-cart",JSON.stringify(cart));renderCart();document.getElementById("cartCount").textContent=cart.reduce(function(s,x){return s+x.qty},0)}
function renderCart(){var el=document.getElementById("cartItems");if(!cart.length){el.innerHTML='<div class="empty">Seu carrinho está vazio.<br>Escolha algumas peças para começar.</div>';return}var out="";cart.forEach(function(x,i){out+='<div class="cart-item"><img src="'+x.img+'" alt=""><div><b>'+x.name+'</b><div class="small">'+x.cat+'</div><div class="qty"><button data-act="minus" data-i="'+i+'">−</button><span>'+x.qty+'</span><button data-act="plus" data-i="'+i+'">+</button></div></div><button class="close" data-act="remove" data-i="'+i+'">×</button></div>'});el.innerHTML=out}
grid.addEventListener("click",function(e){var c=e.target.closest(".card");if(!c)return;current=products[Number(c.dataset.i)];document.getElementById("pmImage").src=current.img;document.getElementById("pmName").textContent=current.name;document.getElementById("pmTag").textContent=current.cat;document.getElementById("pmDesc").textContent=current.desc;document.getElementById("productOverlay").classList.add("show")});
document.querySelectorAll(".filter").forEach(function(b){b.onclick=function(){document.querySelectorAll(".filter").forEach(function(x){x.classList.remove("active")});b.classList.add("active");render(b.dataset.filter)}});
document.getElementById("addProduct").onclick=function(){var old=cart.find(function(x){return x.name===current.name});if(old)old.qty++;else cart.push({name:current.name,cat:current.cat,img:current.img,qty:1});save();document.getElementById("productOverlay").classList.remove("show");document.getElementById("cartOverlay").classList.add("show")};
document.getElementById("cartBtn").onclick=function(){document.getElementById("cartOverlay").classList.add("show")};document.getElementById("closeCart").onclick=function(){document.getElementById("cartOverlay").classList.remove("show")};document.getElementById("closeProduct").onclick=function(){document.getElementById("productOverlay").classList.remove("show")};
document.getElementById("cartOverlay").addEventListener("click",function(e){var b=e.target.closest("[data-act]");if(!b)return;var i=Number(b.dataset.i),a=b.dataset.act;if(a==="plus")cart[i].qty++;if(a==="minus"){cart[i].qty--;if(cart[i].qty<1)cart.splice(i,1)}if(a==="remove")cart.splice(i,1);save()});
document.getElementById("clearCart").onclick=function(){cart=[];save()};
document.getElementById("sendOrder").onclick=function(){if(!cart.length)return;var lines=cart.map(function(x){return "• "+x.name+" — quantidade: "+x.qty}).join("\n");var msg="Olá! Quero fazer um pedido na MP Boutique:\n\n"+lines+"\n\nGostaria de confirmar disponibilidade, tamanhos, cores e valores.";window.open("https://wa.me/559182777239?text="+encodeURIComponent(msg),"_blank")};
document.getElementById("year").textContent=new Date().getFullYear();render("Todos");save();